name: Build iOS development client

defaults:
  tools:
    node: '22'
    pnpm: '10.13.1'

on:
  workflow_dispatch: {}

jobs:
  build_ios:
    name: Build installable development client
    type: build
    environment: development
    params:
      platform: ios
      profile: development
